services:
  db:
    # image: postgres:16
    image: pgvector/pgvector:pg16
    restart: always
    volumes:
      - ./data/postgresql/data:/var/lib/postgresql/data
    ports:
      - "$POSTGRES_PORT:5432"
    env_file:
      - .env
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB